// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
import { z } from "npm:zod@^4.4.3";
var list_posts_default = defineTool({
  name: "list_posts",
  title: "List published posts",
  description: "List published articles from the Freigeist Kongress site. Returns id, title, subtitle, category, published_at, and reading_time. Filter by category slug or full-text query.",
  inputSchema: {
    query: z.string().optional().describe("Optional search text matched against title/subtitle/content."),
    category_slug: z.string().optional().describe("Optional category slug to filter by."),
    limit: z.number().int().min(1).max(50).default(20).describe("Max results to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category_slug, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("posts").select("id, title, subtitle, category_slug, published_at, reading_time, excerpt").eq("status", "published").is("deleted_at", null).order("published_at", { ascending: false, nullsFirst: false }).limit(limit);
    if (category_slug) q = q.eq("category_slug", category_slug);
    if (query) q = q.or(`title.ilike.%${query}%,subtitle.ilike.%${query}%,excerpt.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.96.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_post_default = defineTool2({
  name: "get_post",
  title: "Get post by id or slug",
  description: "Fetch the full content of a single published article by its id (uuid) or slug. Returns title, subtitle, body content, category, and publish date.",
  inputSchema: {
    id_or_slug: z2.string().min(1).describe("Post uuid or slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id_or_slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id_or_slug);
    const { data, error } = await supabase.from("posts").select("*").eq("status", "published").is("deleted_at", null).eq(isUuid ? "id" : "slug", id_or_slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.96.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all article categories with their slug and name.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("categories").select("*").order("name");
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "freigeist-kongress-mcp",
  title: "Freigeist Kongress MCP",
  version: "0.1.0",
  instructions: "Read-only access to published articles on the Freigeist Kongress site. Use `list_categories` to see topics, `list_posts` to browse or search articles (optionally by category), and `get_post` to fetch the full body of a single article by id or slug.",
  tools: [list_posts_default, get_post_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
